# Generated by Django 4.1 on 2022-09-27 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('authority', models.BigIntegerField(primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=200)),
                ('mobile', models.CharField(blank=True, max_length=11, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('amount', models.IntegerField()),
                ('reference_id', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
